runtime: python27
api_version: 1
threadsafe: true
skip_files:
  - ^node_modules/(.*/)?
  - ^.angular/(.*/)?
handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
  - url: /
    static_dir: dist
    secure: always
    http_headers:
      Access-Control-Allow-Origin: '*'
